services:
  - type: web
    name: marketselect
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GRB_WLSACCESSID
        sync: false
      - key: GRB_WLSSECRET
        sync: false
      - key: GRB_LICENSEID
        sync: false
